### ISSUE TITLE
Frontend unit tests fail on some time zones

### ISSUE THREAD

**Issue by VSirvio** [Slowers-Team/Slowers-App#98]
**Describe the bug**
The frontend unit test `renders FlowerList with correct flowers and has the correct number of delete buttons` in `tests/components/FlowerList.test.jsx` fails when the time zone of the system running the unit tests is set to certain time zones (possibly with anything else than `Europe/Helsinki`).

**To Reproduce**
1. Set the system time zone to e.g. `Australia/Canberra` (In Ubuntu-based systems you can do this e.g. by running `sudo timedatectl set-timezone Australia/Canberra`)
2. Run frontend unit tests (i.e. run `npm test` inside the `frontend` directory)
3. The frontend unit test `renders FlowerList with correct flowers and has the correct number of delete buttons` in `tests/components/FlowerList.test.jsx` fails

**Expected behavior**
All frontend unit tests should pass regardless of which time zone you have set for your system.

**Additional context**
The `npm test` output when the system time zone is set to `Australia/Canberra`:
```
> frontend@0.0.0 test
> vitest run


 RUN  v2.1.1 /home/vasirvio/Slowers-App/frontend

stderr | tests/components/RegisterForm.test.jsx > clears input values after successful submit
Error: Not implemented: window.alert
    at module.exports (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at /home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:960:7
    at addUser (/home/vasirvio/Slowers-App/frontend/src/components/RegisterForm.jsx:31:9)
    at HTMLUnknownElement.callCallback (/home/vasirvio/Slowers-App/frontend/node_modules/react-dom/cjs/react-dom.development.js:4164:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
    at invokeEventListeners (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLUnknownElementImpl._dispatch (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLUnknownElementImpl.dispatchEvent (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLUnknownElement.dispatchEvent (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34) undefined

stderr | tests/components/RegisterForm.test.jsx > calls createNewUser with correct values on submit
Error: Not implemented: window.alert
    at module.exports (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at /home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:960:7
    at addUser (/home/vasirvio/Slowers-App/frontend/src/components/RegisterForm.jsx:31:9)
    at HTMLUnknownElement.callCallback (/home/vasirvio/Slowers-App/frontend/node_modules/react-dom/cjs/react-dom.development.js:4164:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
    at invokeEventListeners (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLUnknownElementImpl._dispatch (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLUnknownElementImpl.dispatchEvent (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLUnknownElement.dispatchEvent (/home/vasirvio/Slowers-App/frontend/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34) undefined

stdout | tests/services/flowers.test.js > creates a flower correctly and uses the correct url
{
  name: 'Lily',
  latin_name: 'Lilium',
  added_time: '2024-09-23T11:11:11.000Z'
}

 ✓ tests/components/FlowerForm.test.jsx (4) 389ms
 ❯ tests/components/FlowerList.test.jsx (3)
   ✓ renders FlowerList without flowers
   × renders FlowerList with correct flowers and has the correct number of delete buttons
   ✓ calls deleteFlower when delete button is clicked
 ✓ tests/components/LangSelect.test.jsx (3)
 ✓ tests/components/LogInForm.test.jsx (3) 390ms
 ✓ tests/components/RegisterForm.test.jsx (6) 1188ms
 ✓ tests/services/flowers.test.js (4)
 ✓ tests/services/users.test.js (1)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  tests/components/FlowerList.test.jsx > renders FlowerList with correct flowers and has the correct number of delete buttons
TestingLibraryElementError: Unable to find an element with the text: 8.2.1999 17:16. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.                               
                                                                                                                                            
Ignored nodes: comments, script, style                                                                                                      
<body>                                                                                                                                      
  <div>                                                                                                                                     
    <table                                                                                                                                  
      id="flowerList"                                                                                                                       
    >                                                                                                                                       
      <thead>                                                                                                                               
        <tr>                                                                                                                                
          <th>                                                                                                                              
            Name                                                                                                                            
          </th>
          <th>                                                                                                                              
            Latin name                                                                                                                      
          </th>
          <th>                                                                                                                              
            Added time                                                                                                                      
          </th>
        </tr>                                                                                                                               
      </thead>                                                                                                                              
      <tbody>                                                                                                                               
        <tr>                                                                                                                                
          <td>                                                                                                                              
            Sunflower                                                                                                                       
          </td>
          <td>                                                                                                                              
            <em>                                                                                                                            
              Helianthus annuus                                                                                                             
            </em>
          </td>                                                                                                                             
          <td>                                                                                                                              
            9.2.1999 2:16                                                                                                                   
          </td>
          <td>                                                                                                                              
            <button                                                                                                                         
              id="deleteFlowerButton"                                                                                                       
            >                                                                                                                               
              Delete                                                                                                                        
            </button>
          </td>                                                                                                                             
        </tr>                                                                                                                               
        <tr>                                                                                                                                
          <td>                                                                                                                              
            Lily                                                                                                                            
          </td>
          <td>                                                                                                                              
            <em>                                                                                                                            
              Lilium                                                                                                                        
            </em>
          </td>                                                                                                                             
          <td>                                                                                                                              
            1.1.2024 20:11                                                                                                                  
          </td>
          <td>                                                                                                                              
            <button                                                                                                                         
              id="deleteFlowerButton"                                                                                                       
            >                                                                                                                               
              Delete                                                                                                                        
            </button>
          </td>                                                                                                                             
        </tr>                                                                                                                               
      </tbody>                                                                                                                              
    </table>                                                                                                                                
  </div>                                                                                                                                    
</body>                                                                                                                                     
 ❯ Object.getElementError node_modules/@testing-library/dom/dist/config.js:37:19
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:76:38
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:52:17
 ❯ node_modules/@testing-library/dom/dist/query-helpers.js:95:19
 ❯ tests/components/FlowerList.test.jsx:41:19
     39|     expect(screen.getByText('Lilium')).toBeInTheDocument()
     40| 
     41|     expect(screen.getByText('8.2.1999 17:16')).toBeInTheDocument()
       |                   ^
     42|     expect(screen.getByText('1.1.2024 11:11')).toBeInTheDocument()
     43| 

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 6 passed (7)
      Tests  1 failed | 23 passed (24)
   Start at  04:53:35
   Duration  9.30s (transform 225ms, setup 1.45s, collect 918ms, tests 2.24s, environment 2.78s, prepare 490ms)
```

**Comment by amandahamynen** [comment]
This should be fixed by creating a file ```vitest.global-setup.js``` with

```js
export const setup = () => {
  process.env.TZ = 'UTC-02:00'
}
```
and then adding 

```js
test: {
    …
    globalSetup: './vitest.global-setup.js',
  },
```
into ```vite.config.js``` file.

I tested this on my local machine, and it should address the problem.

Source: https://stackoverflow.com/questions/76911900/setting-a-timezone-in-vitest

**Comment by VSirvio** [comment]
Nice! Could you implement it and create a pull request?
